### ISSUE TITLE
bottom >= 0.10.0 requires new configuration format for colors

### ISSUE THREAD

**Issue by patricklewis** [catppuccin/bottom#6]
[bottom 0.10.0](https://github.com/ClementTsang/bottom/releases/tag/0.10.0) was released on 2024-08-01 and introduced a new configuration format for themes/styling (see [bottom#1499](https://github.com/ClementTsang/bottom/pull/1499) for specifics).

As of version 0.10.0, bottom no longer supports the `[colors]` configuration used by the theme files in this repo.

bottom's new default configuration file instead has sections like `[styles.cpu]`, `[styles.network]`, etc.

https://clementtsang.github.io/bottom/0.10.2/configuration/config-file/styling/ lists the full set of values that can be configured in the configuration file.

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for letting us know. This repository currently has no maintainer so PRs are most definitely welcome! I understand that bottom 0.10.0 now defaults to terminal colours so it should be styled by default if the person is using Catppuccin in their terminal. 

Although I think it would be nice to update this repository with the updated keys. I can't promise I'll get around to this in the future but I'm happy to be requested for review on any PRs!

This repository uses [catppuccin/whiskers](https://github.com/catppuccin/whiskers) to generate the configuration files so the PR would need to edit the `.tera` file at the root of the repository and run whiskers in the command line for the files to be updated/generated.
